### ISSUE TITLE
Error while deploying logic

### ISSUE THREAD

**Issue by sarvalabs-harshrastogi** [sarvalabs/js-moi-sdk#38]
### Description
While deploying the logic getting the below error:

```bash
harshrastogi@Harsh-Rastogi scripts % npx ts-node src
(node:57101) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Deploying Logic Using Address: 0x2835c601ccd1fc6518ae17b58dc91a644d43b734001dd2cd262a51f03a3fafef
Interaction Hash:  {
  hash: '0xf2f2ef3c4f2718d40c85901217a50e29639d8b656f31d171c11029fc71926ca1',
  wait: [Function: bound waitForInteraction] AsyncFunction,
  result: [Function: bound processResult] AsyncFunction
}
/Users/harshrastogi/Developer/sarva-labs/js-moi-sdk/packages/js-moi-utils/dist/errors.js:72
        throw new CustomError(message, code, params);
              ^
CustomError: grid hash not found: key not found
    at Function.throwError (/Users/harshrastogi/Developer/sarva-labs/js-moi-sdk/packages/js-moi-utils/dist/errors.js:72:15)
    at JsonRpcProvider.processResponse (/Users/harshrastogi/Developer/sarva-labs/js-moi-sdk/packages/js-moi-providers/dist/base-provider.js:44:39)
    at JsonRpcProvider.getInteractionReceipt (/Users/harshrastogi/Developer/sarva-labs/js-moi-sdk/packages/js-moi-providers/dist/base-provider.js:611:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployTodoLogic (/Users/harshrastogi/Developer/scripts/src/Todo/logic.ts:44:21)
    at async deploy (/Users/harshrastogi/Developer/scripts/src/index.ts:59:5) {
  code: 'ERROR_SERVER',
  reason: 'grid hash not found: key not found',
  params: {}
}
```

**Comment by sarvalabs-harshrastogi** [comment]
closed in #37
