### ISSUE TITLE
Integrate the latest version of JS-POLO

### ISSUE THREAD

**Issue by sarvalabs-harshrastogi** [sarvalabs/js-moi-sdk#48]
### Description

The current integration of JS-MOI-SDK within our project encounters an exception when attempting to depolarize an empty Map. The resolution to this is upgrading new JS-POLO to a latest version

### Logs
```bash
Error: load convert fail: not a compound wire 
at ReadBuffer.load (readbuffer.js:49:1)
at Depolorizer.newLoadDepolorizer (depolorizer.js:78:1)
at Depolorizer.depolorizeMap (depolorizer.js:296:1)
at Depolorizer.depolorize (depolorizer.js:109:1)
at depolorizer.js:349:1
at Array.forEach (<anonymous>)
at Depolorizer.depolorizeStruct (depolorizer.js:346:1)
at Depolorizer.depolorize (depolorizer.js:111:1)
at Depolorizer.depolorizeArray (depolorizer.js:223:1)
```

**Comment by sarvalabs-harshrastogi** [comment]
closed in #49
